applications/music/urls.py
from django.conf.urls.static import static
from django.conf.urls import include, url

from .views import (
   #Other
   HomeView,
   AlbumListView,
   #CRUD
   AlbumCreateView,
   AlbumDetailView,
   AlbumUpdateView,
   AlbumDeleteView
   )


urlpatterns = [
   url(r'^home/$', HomeView.as_view(), name='album_home'),
   url(r'^list/$', AlbumListView.as_view(), name='album_list'),


   #########
   # CRUD  #
   #########
   #Create
   url(r'^create/$', AlbumCreateView.as_view(), name='album_create'),
   #Read (Detail/Show)
   url(r'^(?P<pk>\d+)/$', AlbumDetailView.as_view(), name='album_detail'),
   #Update
   url(r'^update/(?P<pk>\d+)/$', AlbumUpdateView.as_view(), name='album_update'),
   #Delete
   url(r'^delete/(?P<pk>\d+)/$', AlbumDeleteView.as_view(), name='album_delete'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
     url(r'^music/', include('applications.music.urls', namespace='music')),
     url(r'^blog/', include('applications.blog.urls', namespace='blog')),
     url(r'^ecommerce/', include('applications.ecommerce.urls', namespace='ecommerce')),
     url(r'^cardealer/', include('applications.cardealer.urls', namespace='cardealer')),
     url(r'^', include('applications.cardealer.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/music/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.contrib.auth.models import User
from .models_utils import TimeStampedModel
from django.core.urlresolvers import reverse_lazy, reverse
from django.utils import timezone
from datetime import datetime, timedelta

def upload_to(instance, filename):
    return "%s/%s" % (instance._meta.app_label, filename)

class Album(TimeStampedModel, models.Model):
    #user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=30, blank=False, null=False )
    artist_name = models.CharField(max_length=30, blank=False, null=False )
    nb_title = models.PositiveSmallIntegerField()
    description = models.TextField(max_length=500, blank=True, null=True )
    birth_date = models.DateField(default="1995-01-01")
    image = models.ImageField(
                    upload_to=upload_to,
                    null=True, blank=True
                     )

    def __str__(self):
    	return str(self.title)

    class Meta:
        verbose_name_plural = "Albums"
        verbose_name = "Album"


    def get_absolute_url(self):
        return reverse('album_detail', kwargs={'pk':self.id})

applications/music/forms.py
from django.forms import ModelForm
from .models import Album

class AlbumForm(ModelForm):
	class Meta:
		model = Album
		fields = ['title', 'artist_name', 'nb_title', 'description']

'''
description
birth_date
image
'''

applications/music/views.py
from datetime import datetime
from django.core.urlresolvers import reverse, reverse_lazy

#Class Based View
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

#Protected
from braces.views import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

#messages
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

#django-friendship
#from friendship.models import Friend, Follow    

#models
from .models  import Album
from .forms  import AlbumForm

#forms
#from .forms import ( ProductForm, ProductEditForm )

class HomeView(TemplateView):
    template_name = 'music/album_list.html'

class AlbumListView(ListView):
    model = Album
    template_name = 'music/album_list.html'
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super(AlbumListView, self).get_context_data(**kwargs)
        context['now'] = datetime.now()
        return context

    def get_queryset(self):
        return Album.objects.all()#filter(status__iexact=Article.STATUS.active)

    def get_paginate_by(self, queryset):
        """ Paginate by specified value in querystring, or use default class property value.  """
        return self.request.GET.get('paginate_by', self.paginate_by)

album_list = AlbumListView.as_view()


class AlbumCreateView(SuccessMessageMixin, CreateView):
    form_class = AlbumForm
    template_name = "music/album_create.html"
    success_message = 'Successfully Added a Post entry'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        #self.object.author = self.request.user
        return super(AlbumCreateView, self).form_valid(form)

album_new = login_required(AlbumCreateView.as_view())


class AlbumDetailView(DetailView):
    model = Album
    template_name = 'music/album_detail.html'

    def get_context_data(self, **kwargs):
        context = super(AlbumDetailView, self).get_context_data(**kwargs)
        context['now'] = datetime.now()
        return context

album_detail = AlbumDetailView.as_view()

class AlbumUpdateView(SuccessMessageMixin, UpdateView):
    model = Album
    form_class = AlbumForm
    template_name = "music/album_create.html"
    success_message = 'Successfully Updated a Post entry'

    def dispatch(self, *args, **kwargs):
        return super(self.__class__, self).dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        #migh need to remove that line
        #self.object.author = self.request.user
        return super(self.__class__, self).form_valid(form)

album_update = login_required(AlbumUpdateView.as_view())


class  AlbumDeleteView(SuccessMessageMixin, DeleteView):
    model = Album
    success_message = 'Successfully Deleted a Post entry'
    success_url = reverse_lazy('music:album_list')

    def dispatch(self, request, *args, **kwargs):
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
    	messages.success(self.request, self.success_message)
    	return super(self.__class__, self).delete(request, *args, **kwargs)

applications/music/templates/music/album_create.html
{% extends 'music/base.html' %}
{% load staticfiles %}

{% block style %}
{% endblock %}


{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-10 col-lg-1-offset">
			<form action="." method="post">
			    {% csrf_token %}
			    {{ form.as_p }}
			    <input type="submit" value="Submit" />
			</form>
			
		</div>
	</div>
</div>

{% endblock %}

applications/music/templates/music/album_detail.html
{% extends 'music/base.html' %}
{% load staticfiles %}

{% block style %}
{% endblock %}



{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-10 col-lg-1-offset">
			<p>ID: {{ object.id }}</p>
			<p>Title: {{ object.title }}</p>
			<p>Artist: {{ object.artist_name }}</p>
			<p>Description: {{ object.description }}</p>
			<p>Birth_date: {{ object.birth_date }}</p>
			<p>Image_url: {{ object.image }}</p>
		</div>
	</div>
</div>


{% endblock %}

applications/music/templates/music/album_list.html
{% extends 'music/base.html' %}
{% load staticfiles %}

 	{% block style %}
	{% endblock %}

	

	{% block content %}
	
	<div class="container">
		<div class="row">
			<div class="col-lg-10 col-lg-offset-1">
				<h2>
				<a class="btn right btn-md" href="{% url 'album_create' %}">Create Album</a></h2>
			
			 <h2>Music ListView</h2>
			  <table class="table table-bordered">
			    <thead>
			      <tr>
			        <th>Title</th>
			        <th>artist_name</th>
			        <th>nb_title</th>
			        <th></th>
			        <th></th>
			        <th></th>
			      </tr>
			    </thead>
			    <tbody>
				{% for music in object_list %}
			      <tr>
			        <td>{{music.title}}</td>
			        <td>{{music.artist_name}}</td>
			        <td>{{music.nb_title}}</td>
			        <td>
			        	<a href="{% url 'music:album_detail' music.id %}" class="btn btn-info btn-sm">Show</a>
			        </td>
			        <td>
			        	<a href="{% url 'music:album_update' music.id %}" class="btn btn-warning btn-sm">Update</a>
			        </td>
			        <td>
			         <form class="right" method="POST" action="{% url 'album_delete' music.id %}">
				         {% csrf_token %}<input class="btn btn-danger btn-sm" type="submit" value="DELETE">
				      </form>
			        </td>
			      </tr>
				{% endfor %}
			    </tbody>
			  </table>
			</div>
		</div>
	</div>
	
		
	
	
	{% endblock %}

applications/music/templates/music/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Wadiyabi</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/paper/bootstrap.min.css" rel="stylesheet" integrity="sha384-awusxf8AUojygHf2+joICySzB780jVvQaVCAt1clU3QsyAitLGul28Qxb2r1e5g+" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

      <script type="text/javascript" src="https://js.stripe.com/v2/"></script>


<style>
	
body {
  padding-top: 50px;
}
.starter-template {
  padding: 40px 15px;
  text-align: center;
}

</style>
</head>
<body>

  {% include 'music/includes/navbar.html' %}
  {% include 'music/includes/jumbotron.html' %}

  {% block content %}
  {% endblock %}
  


</body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>