applications/blog/urls.py
from django.conf.urls.static import static
from django.conf.urls import include, url

from .views import (
	#Other
	HomeView,
	ArticleListView,
	#CRUD
	ArticleCreateView,
	ArticleDetailView,
	ArticleUpdateView,
	ArticleDeleteView
	)


urlpatterns = [
   url(r'^home/$', HomeView.as_view(), name='blog_home'),
   url(r'^list/$', ArticleListView.as_view(), name='article_list'),


   #########
   # CRUD  #
   #########
   #Create
   url(r'^create/$', ArticleCreateView.as_view(), name='article_create'),
   #Read (Detail/Show)
   url(r'^(?P<pk>\d+)/$', ArticleDetailView.as_view(), name='article_detail'),
   #Update
   url(r'^update/(?P<pk>\d+)/$', ArticleUpdateView.as_view(), name='article_update'),
   #Delete
   url(r'^delete/(?P<pk>\d+)/$', ArticleDeleteView.as_view(), name='article_delete'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
     url(r'^music/', include('applications.music.urls', namespace='music')),
     url(r'^blog/', include('applications.blog.urls', namespace='blog')),
     url(r'^ecommerce/', include('applications.ecommerce.urls', namespace='ecommerce')),
     url(r'^cardealer/', include('applications.cardealer.urls', namespace='cardealer')),
     url(r'^', include('applications.cardealer.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/blog/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.contrib.auth.models import User
from applications.music.models_utils import TimeStampedModel
from django.core.urlresolvers import reverse
from django.utils import timezone
from datetime import datetime, timedelta

def upload_to(instance, filename):
    return "%s/%s" % (instance._meta.app_label, filename)

class Article(TimeStampedModel, models.Model):
    #user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=30, blank=False, null=False )
    description = models.TextField(max_length=500, blank=False, null=False )
    image = models.ImageField(
                    upload_to=upload_to,
                    null=False, blank=False
                     )

    def __str__(self):
    	return str(self.title)

    class Meta:
        verbose_name_plural = "Articles"
        verbose_name = "Article"


    def get_absolute_url(self):
        return reverse('article_detail', kwargs={'pk':self.id})

applications/blog/forms.py
from django.forms import ModelForm
from .models import Article

class ArticleForm(ModelForm):
	class Meta:
		model = Article
		fields = ['title',  'description', 'image']

applications/blog/views.py
from datetime import datetime
from django.core.urlresolvers import reverse, reverse_lazy

#Class Based View
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

#Protected
from braces.views import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

#messages
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

#django-friendship
#from friendship.models import Friend, Follow    

#models
from .models  import Article
from .forms  import ArticleForm

from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    template_name = 'blog/article_list.html'


class ArticleListView(ListView):
    model = Article
    template_name = 'blog/article_list.html'
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        context['now'] = datetime.now()
        return context

    def get_queryset(self):
        return Article.objects.all()#filter(status__iexact=Article.STATUS.active)

    def get_paginate_by(self, queryset):
        """ Paginate by specified value in querystring, or use default class property value.  """
        return self.request.GET.get('paginate_by', self.paginate_by)

article_list = ArticleListView.as_view()


class ArticleCreateView(SuccessMessageMixin, CreateView):
    form_class = ArticleForm
    template_name = "blog/article_create.html"
    success_message = 'Successfully Added a Post entry'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        #self.object.author = self.request.user
        return super(ArticleCreateView, self).form_valid(form)

article_new = login_required(ArticleCreateView.as_view())

class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blog/article_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        context['now'] = datetime.now()
        return context

article_detail = ArticleDetailView.as_view()

class ArticleUpdateView(SuccessMessageMixin, UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = "blog/article_create.html"
    success_message = 'Successfully Updated a Post entry'

    def dispatch(self, *args, **kwargs):
        return super(self.__class__, self).dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        #migh need to remove that line
        #self.object.author = self.request.user
        return super(self.__class__, self).form_valid(form)

article_update = login_required(ArticleUpdateView.as_view())


class  ArticleDeleteView(SuccessMessageMixin, DeleteView):
    model = Article
    success_message = 'Successfully Deleted a Post entry'
    success_url = reverse_lazy('blog:article_list')

    def dispatch(self, request, *args, **kwargs):
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
    	messages.success(self.request, self.success_message)
    	return super(self.__class__, self).delete(request, *args, **kwargs)

applications/blog/templates/blog/article_create.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block style %}
{% endblock %}


{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-10 col-lg-1-offset">
			<form action="." method="post" enctype="multipart/form-data">
			    {% csrf_token %}
			    {{ form.as_p }}
			    <input type="submit" value="Submit" />
			</form>
			
		</div>
	</div>
</div>

{% endblock %}

applications/blog/templates/blog/article_detail.html
{% extends 'music/base.html' %}
{% load staticfiles %}

{% block style %}
{% endblock %}



{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-10 col-lg-1-offset">
			<p>ID: {{ object.id }}</p>
			<p>Title: {{ object.title }}</p>
			<p>Description: {{ object.description }}</p>
			<p>Image_url: {{ object.image }}</p>
		</div>
	</div>
</div>


{% endblock %}

applications/blog/templates/blog/article_list.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

 	{% block style %}
	{% endblock %}

	

	{% block content %}
	
	<div class="container">
		<div class="row">
			<div class="col-lg-10 col-lg-offset-1">
				<h2>
				<a class="btn right btn-md" href="{% url 'blog:article_create' %}">Create Article</a></h2>
			
			 <h2>Music ListView</h2>
			  <table class="table table-bordered">
			    <thead>
			      <tr>
			        <th>Title</th>
			        <th>description</th>
			        <th>image</th>
			        <th></th>
			        <th></th>
			        <th></th>
			      </tr>
			    </thead>
			    <tbody>
				{% for article in object_list %}
			      <tr>
			        <td>{{article.title}}</td>
			        <td>{{article.description|truncatechars:100 }}</td>
			        <td>{{article.image.url}}</td>
			        <td>
			        	<a href="{% url 'blog:article_detail' article.id %}" class="btn btn-info btn-sm">Show</a>
			        </td>
			        <td>
			        	<a href="{% url 'blog:article_update' article.id %}" class="btn btn-warning btn-sm">Update</a>
			        </td>
			        <td>
			         <form class="right" method="POST" action="{% url 'blog:article_delete' article.id %}">
				         {% csrf_token %}<input class="btn btn-danger btn-sm" type="submit" value="DELETE">
				      </form>
			        </td>
			      </tr>
				{% endfor %}
			    </tbody>
			  </table>
			</div>
		</div>
	</div>
	
		
	
	
	{% endblock %}