applications/cardealer/urls.py
from django.conf.urls.static import static
from django.conf.urls import include, url

from .views import (
	#Other
	HomeView,
	CarListView,
	#CRUD
	CarCreateView,
	CarDetailView,
	CarUpdateView,
	CarDeleteView
	)


urlpatterns = [
   url(r'^home/$', HomeView.as_view(), name='cardealer_home'),
   url(r'^list/$', CarListView.as_view(), name='car_list'),


   #########
   # CRUD  #
   #########
   #Create
   url(r'^create/$', CarCreateView.as_view(), name='car_create'),
   #Read (Detail/Show)
   url(r'^(?P<pk>\d+)/$', CarDetailView.as_view(), name='car_detail'),
   #Update
   url(r'^update/(?P<pk>\d+)/$', CarUpdateView.as_view(), name='car_update'),
   #Delete
   url(r'^delete/(?P<pk>\d+)/$', CarDeleteView.as_view(), name='car_delete'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
     url(r'^music/', include('applications.music.urls', namespace='music')),
     url(r'^blog/', include('applications.blog.urls', namespace='blog')),
     url(r'^ecommerce/', include('applications.ecommerce.urls', namespace='ecommerce')),
     url(r'^cardealer/', include('applications.cardealer.urls', namespace='cardealer')),
     url(r'^', include('applications.cardealer.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/cardealer/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.contrib.auth.models import User
from applications.music.models_utils import TimeStampedModel
from django.core.urlresolvers import reverse
from django.utils import timezone
from datetime import datetime, timedelta

def upload_to(instance, filename):
    return "%s/%s" % (instance._meta.app_label, filename)

class Car(TimeStampedModel, models.Model):
    #user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    car_name = models.CharField(max_length=30, blank=False, null=False )
    car_model = models.CharField(max_length=30, blank=False, null=False )
    description = models.TextField(max_length=500, blank=False, null=False )
    image = models.ImageField(
                    upload_to=upload_to,
                    null=False, blank=False
                     )
    price = models.DecimalField(max_digits=5, decimal_places=2, blank=False, null=False )

    def __str__(self):
    	return str(self.car_name)

    class Meta:
        verbose_name_plural = "Cars"
        verbose_name = "Car"


    def get_absolute_url(self):
        return reverse('car_detail', kwargs={'pk':self.id})

applications/cardealer/forms.py
from django.forms import ModelForm
from .models import Car

class CarForm(ModelForm):
	class Meta:
		model = Car
		fields = ['car_name', 'car_model', 'description', 'image', 'price']

applications/cardealer/views.py
from datetime import datetime
from django.core.urlresolvers import reverse, reverse_lazy

#Class Based View
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

#Protected
from braces.views import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

#messages
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

#django-friendship
#from friendship.models import Friend, Follow    

#models
from .models  import Car
from .forms  import CarForm

from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    template_name = 'cardealer/car_list.html'


class CarListView(ListView):
    model = Car
    template_name = 'cardealer/car_list.html'
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super(CarListView, self).get_context_data(**kwargs)
        context['now'] = datetime.now()
        return context

    def get_queryset(self):
        return Car.objects.all()#filter(status__iexact=Car.STATUS.active)

    def get_paginate_by(self, queryset):
        """ Paginate by specified value in querystring, or use default class property value.  """
        return self.request.GET.get('paginate_by', self.paginate_by)

car_list = CarListView.as_view()


class CarCreateView(SuccessMessageMixin, CreateView):
    form_class = CarForm
    template_name = "cardealer/car_create.html"
    success_message = 'Successfully Added a Post entry'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        #self.object.author = self.request.user
        return super(CarCreateView, self).form_valid(form)

car_new = login_required(CarCreateView.as_view())

class CarDetailView(DetailView):
    model = Car
    template_name = 'cardealer/car_detail.html'

    def get_context_data(self, **kwargs):
        context = super(CarDetailView, self).get_context_data(**kwargs)
        context['now'] = datetime.now()
        return context

car_detail = CarDetailView.as_view()

class CarUpdateView(SuccessMessageMixin, UpdateView):
    model = Car
    form_class = CarForm
    template_name = "cardealer/car_create.html"
    success_message = 'Successfully Updated a Post entry'

    def dispatch(self, *args, **kwargs):
        return super(self.__class__, self).dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        #migh need to remove that line
        #self.object.author = self.request.user
        return super(self.__class__, self).form_valid(form)

car_update = login_required(CarUpdateView.as_view())


class  CarDeleteView(SuccessMessageMixin, DeleteView):
    model = Car
    success_message = 'Successfully Deleted a Post entry'
    success_url = reverse_lazy('cardealer:car_list')

    def dispatch(self, request, *args, **kwargs):
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
    	messages.success(self.request, self.success_message)
    	return super(self.__class__, self).delete(request, *args, **kwargs)

applications/cardealer/templates/cardealer/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Wadiyabi</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/paper/bootstrap.min.css" rel="stylesheet" integrity="sha384-awusxf8AUojygHf2+joICySzB780jVvQaVCAt1clU3QsyAitLGul28Qxb2r1e5g+" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

      <script type="text/javascript" src="https://js.stripe.com/v2/"></script>


<style>
	
body {
  padding-top: 50px;
}
.starter-template {
  padding: 40px 15px;
  text-align: center;
}

</style>
</head>
<body>

  {% include 'blog/includes/navbar.html' %}
  {% include 'blog/includes/jumbotron.html' %}

  {% block content %}
  {% endblock %}
  


</body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

applications/cardealer/templates/cardealer/car_create.html
{% extends 'ecommerce/base.html' %}
{% load staticfiles %}

{% block style %}
{% endblock %}


{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-10 col-lg-1-offset">
			<form action="." method="post" enctype="multipart/form-data">
			    {% csrf_token %}
			    {{ form.as_p }}
			    <input type="submit" value="Submit" />
			</form>
			
		</div>
	</div>
</div>

{% endblock %}

applications/cardealer/templates/cardealer/car_detail.html
{% extends 'ecommerce/base.html' %}
{% load staticfiles %}

{% block style %}
{% endblock %}



{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-10 col-lg-1-offset">
			<p>ID: {{ object.id }}</p>
			<p>Title: {{ object.car_name }}</p>
			<p>Title: {{ object.car_model }}</p>
			<p>Description: {{ object.description }}</p>
			<p>Image_url: {{ object.image }}</p>
			<p>price: {{ object.price }}</p>
			<p>Show Image <br>
				<img src="{{ object.image.url }}"/>
			</p>
		</div>
	</div>
</div>


{% endblock %}

applications/cardealer/templates/cardealer/car_list.html
{% extends 'cardealer/base.html' %}
{% load staticfiles %}

 	{% block style %}
	{% endblock %}

	{% block content %}
	
	<div class="container">
		<div class="row">
			<div class="col-lg-10 col-lg-offset-1">
				<h2>
				<a class="btn right btn-md" href="{% url 'cardealer:car_create' %}">Create Product</a></h2>
			
			 <h2>Music ListView</h2>
			  <table class="table table-bordered">
			    <thead>
			      <tr>
			        <th>car_name</th>
			        <th>car_model</th>
			        <th>description</th>
			        <th>price</th>
			        <th>image</th>
			        <th></th>
			        <th></th>
			        <th></th>
			      </tr>
			    </thead>
			    <tbody>
				{% for car in object_list %}
			      <tr>
			        <td>{{car.car_name|truncatechars:9}}</td>
			        <td>{{car.car_model|truncatechars:9}}</td>
			        <td>{{car.description|truncatechars:60 }}</td>
			        <td>{{car.price}}</td>
			        <td>{{car.image.url}}</td>
			        <td>
			        	<a href="{% url 'cardealer:car_detail' car.id %}" class="btn btn-info btn-sm">Show</a>
			        </td>
			        <td>
			        	<a href="{% url 'cardealer:car_update' car.id %}" class="btn btn-warning btn-sm">Update</a>
			        </td>
			        <td>
			         <form class="right" method="POST" action="{% url 'cardealer:car_delete' car.id %}">
				         {% csrf_token %}<input class="btn btn-danger btn-sm" type="submit" value="DELETE">
				      </form>
			        </td>
			      </tr>
				{% endfor %}
			    </tbody>
			  </table>
			</div>
		</div>
	</div>
	
		
	
	
	{% endblock %}