applications/ecommerce/urls.py
from django.conf.urls.static import static
from django.conf.urls import include, url

from .views import (
	#Other
	HomeView,
	ProductListView,
	#CRUD
	ProductCreateView,
	ProductDetailView,
	ProductUpdateView,
	ProductDeleteView
	)


urlpatterns = [
   url(r'^home/$', HomeView.as_view(), name='ecommerce_home'),
   url(r'^list/$', ProductListView.as_view(), name='product_list'),


   #########
   # CRUD  #
   #########
   #Create
   url(r'^create/$', ProductCreateView.as_view(), name='product_create'),
   #Read (Detail/Show)
   url(r'^(?P<pk>\d+)/$', ProductDetailView.as_view(), name='product_detail'),
   #Update
   url(r'^update/(?P<pk>\d+)/$', ProductUpdateView.as_view(), name='product_update'),
   #Delete
   url(r'^delete/(?P<pk>\d+)/$', ProductDeleteView.as_view(), name='product_delete'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
     url(r'^music/', include('applications.music.urls', namespace='music')),
     url(r'^blog/', include('applications.blog.urls', namespace='blog')),
     url(r'^ecommerce/', include('applications.ecommerce.urls', namespace='ecommerce')),
     url(r'^cardealer/', include('applications.cardealer.urls', namespace='cardealer')),
     url(r'^', include('applications.cardealer.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/ecommerce/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.contrib.auth.models import User
from applications.music.models_utils import TimeStampedModel
from django.core.urlresolvers import reverse
from django.utils import timezone
from datetime import datetime, timedelta

def upload_to(instance, filename):
    return "%s/%s" % (instance._meta.app_label, filename)

class Product(TimeStampedModel, models.Model):
    #user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=30, blank=False, null=False )
    description = models.TextField(max_length=500, blank=False, null=False )
    image = models.ImageField(
                    upload_to=upload_to,
                    null=False, blank=False
                     )
    price = models.DecimalField(max_digits=5, decimal_places=2, blank=False, null=False )

    def __str__(self):
    	return str(self.title)

    class Meta:
        verbose_name_plural = "Products"
        verbose_name = "Product"


    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'pk':self.id})

applications/ecommerce/forms.py
from django.forms import ModelForm
from .models import Product

class ProductForm(ModelForm):
	class Meta:
		model = Product
		fields = ['title', 'description', 'image', 'price']

applications/ecommerce/views.py
from datetime import datetime
from django.core.urlresolvers import reverse, reverse_lazy

#Class Based View
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

#Protected
from braces.views import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

#messages
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

#django-friendship
#from friendship.models import Friend, Follow    

#models
from .models  import Product
from .forms  import ProductForm

from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    template_name = 'ecommerce/product_list.html'


class ProductListView(ListView):
    model = Product
    template_name = 'ecommerce/product_list.html'
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['now'] = datetime.now()
        return context

    def get_queryset(self):
        return Product.objects.all()#filter(status__iexact=Product.STATUS.active)

    def get_paginate_by(self, queryset):
        """ Paginate by specified value in querystring, or use default class property value.  """
        return self.request.GET.get('paginate_by', self.paginate_by)

product_list = ProductListView.as_view()


class ProductCreateView(SuccessMessageMixin, CreateView):
    form_class = ProductForm
    template_name = "ecommerce/product_create.html"
    success_message = 'Successfully Added a Post entry'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        #self.object.author = self.request.user
        return super(ProductCreateView, self).form_valid(form)

product_new = login_required(ProductCreateView.as_view())

class ProductDetailView(DetailView):
    model = Product
    template_name = 'ecommerce/product_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['now'] = datetime.now()
        return context

product_detail = ProductDetailView.as_view()

class ProductUpdateView(SuccessMessageMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "ecommerce/product_create.html"
    success_message = 'Successfully Updated a Post entry'

    def dispatch(self, *args, **kwargs):
        return super(self.__class__, self).dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        #migh need to remove that line
        #self.object.author = self.request.user
        return super(self.__class__, self).form_valid(form)

product_update = login_required(ProductUpdateView.as_view())


class  ProductDeleteView(SuccessMessageMixin, DeleteView):
    model = Product
    success_message = 'Successfully Deleted a Post entry'
    success_url = reverse_lazy('ecommerce:product_list')

    def dispatch(self, request, *args, **kwargs):
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
    	messages.success(self.request, self.success_message)
    	return super(self.__class__, self).delete(request, *args, **kwargs)

applications/ecommerce/templates/ecommerce/product_create.html
{% extends 'ecommerce/base.html' %}
{% load staticfiles %}

{% block style %}
{% endblock %}


{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-10 col-lg-1-offset">
			<form action="." method="post" enctype="multipart/form-data">
			    {% csrf_token %}
			    {{ form.as_p }}
			    <input type="submit" value="Submit" />
			</form>
			
		</div>
	</div>
</div>

{% endblock %}

applications/ecommerce/templates/ecommerce/product_detail.html
{% extends 'ecommerce/base.html' %}
{% load staticfiles %}

{% block style %}
{% endblock %}



{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-10 col-lg-1-offset">
			<p>ID: {{ object.id }}</p>
			<p>Title: {{ object.title }}</p>
			<p>Description: {{ object.description }}</p>
			<p>Image_url: {{ object.image }}</p>
			<p>price: {{ object.price }}</p>
			<p>Show Image <br>
				<img src="{{ object.image.url }}"/>
			</p>
		</div>
	</div>
</div>


{% endblock %}

applications/ecommerce/templates/ecommerce/product_list.html
{% extends 'ecommerce/base.html' %}
{% load staticfiles %}

 	{% block style %}
	{% endblock %}

	

	{% block content %}
	
	<div class="container">
		<div class="row">
			<div class="col-lg-10 col-lg-offset-1">
				<h2>
				<a class="btn right btn-md" href="{% url 'ecommerce:product_create' %}">Create Product</a></h2>
			
			 <h2>Music ListView</h2>
			  <table class="table table-bordered">
			    <thead>
			      <tr>
			        <th>Title</th>
			        <th>description</th>
			        <th>price</th>
			        <th>image</th>
			        <th></th>
			        <th></th>
			        <th></th>
			      </tr>
			    </thead>
			    <tbody>
				{% for product in object_list %}
			      <tr>
			        <td>{{product.title}}</td>
			        <td>{{product.description|truncatechars:100 }}</td>
			        <td>{{product.price}}</td>
			        <td>{{product.image.url}}</td>
			        <td>
			        	<a href="{% url 'ecommerce:product_detail' product.id %}" class="btn btn-info btn-sm">Show</a>
			        </td>
			        <td>
			        	<a href="{% url 'ecommerce:product_update' product.id %}" class="btn btn-warning btn-sm">Update</a>
			        </td>
			        <td>
			         <form class="right" method="POST" action="{% url 'ecommerce:product_delete' product.id %}">
				         {% csrf_token %}<input class="btn btn-danger btn-sm" type="submit" value="DELETE">
				      </form>
			        </td>
			      </tr>
				{% endfor %}
			    </tbody>
			  </table>
			</div>
		</div>
	</div>
	
		
	
	
	{% endblock %}